### PR TITLE
Correct check in try_polynomial()

### PR DESCRIPTION
**Pull request by skirpichev**
@jksuom, let me know if I can't merge PR's from your SymPy fork on terms of the SymPy license.  I.e. parts of your non-merged-yet work.  I got permission for [Aaron's stuff](https://github.com/diofant/diofant/pull/307#issuecomment-247626007) so far.

- [x] close https://github.com/diofant/diofant/issues/445

### CODE REVIEW

**Comment by jksuom** [comment]
> let me know if I can't merge PR's from your SymPy fork

You can merge. I have no objections.

(BTW, in your method of dealing with shift operators, it seems to me that `a == b` may occur. since common parameters are not removed, but that should not affect the final result.)

**Comment by skirpichev** [comment]
Thank you for permission and review, I'll check code flow again to be sure.

**Comment by skirpichev** [comment]
> it seems to me that a == b may occur.

@jksuom, why do you think so?  ``ReduceOrder`` (which is called by ``_reduce_order()`` helper) should work for ``n=ai-bj=0``.  Your solution sympy/sympy#12182 seems to be correct to, but I have some objections against your first commit.
1) it seems to be a partial duplicate of ``_reduce_order``
2) some reduction operators will be missed in your case, because you preprocess input for ``_reduce_order``

On another hand, difference with mpmath's defaults, [mentioned here](https://github.com/sympy/sympy/pull/10531#issuecomment-281806140) - does matter.  One possible solution: add new evalf helper for ``hyper()``, which will set ``eliminate`` kwarg.  Or even change mpmath's defaults.

Also, new results for cases like ``hyper((-1, 1), (-2,), z)`` are consistent with Mathematica's output.  So, probably it's equally correct, unless you think that the result will be inconsistent for some parameters.

cc @certik

**Comment by jksuom** [comment]
The comment about `a == b` was there only to remind that common parameters had been eliminated. Otherwise the inequality `a > b` should have been written in the form `a >= b`.

> it seems to be a partial duplicate of _reduce_order

Yes, it is. I was thinking of simplifying _reduce_order later in another commit. Using preprocessed parameters (and omitting some parts) to avoid repetition.

> some reduction operators will be missed in your case,

I think that it would only happen in case no shift operators are wanted.

I was thinking of adding kwarg `eliminate` to hyperexpand.

**Comment by skirpichev** [comment]
Looking further, mpmath behaviour wrt "eliminate" flag looks odd.  No matter which definition is used for common nonpositive integer upper and lower parameters - result should be same with or without expansion.

**Comment by skirpichev** [comment]
Ok, at least Fredrik - positive for changing defaults.  This could be merged meanwhile, as a temporary workarround.

**Pull request merged**
