### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by skirpichev**

### CODE REVIEW

**Comment by skirpichev** [comment]
@sachin-4099, just to keep in mind: 90% of information about the diofant project from the sympy devs - is a lie:)  [This](https://github.com/sympy/sympy/issues/18509#issuecomment-581027055) is an excellent example of.  In fact:
-  you freely can use any diofant's code (it's an open source project, after all), just properly quote the source of your contribution (e.g. point to the commit in the diofant's master or to a merged pull request),
-  yes, meaning of assumptions is slightly different, but not too much, just little more clean (no extended_nonzero, extended_positive etc, positive=extended_positive): sympy devs more or less follow my changes, just not always acknowledge it.

So, it's easy to trace down differences and you can see, that in this example - the solution will work, except trivial changes (`Pow._eval_is_positive()` -> `Pow._eval_is_extended_positive()` and `self.exp.is_positive` -> `self.exp.is_extended_positive`).  Hopefully, I can merge this soon (you might help!), I'm just checking for more errors in Pow's assumption helpers, related to handling extended_real's.

**Comment by sachin-4099** [comment]
Hi @skirpichev, can you help me with some existing issues on sympy, which I will merge later but will do a complete work on them, for my gsoc proposal...

**Comment by sachin-4099** [comment]
This is to ensure that I can make a WIP PR on those issues and will continue them in the summers, if selected for gsoc

**Comment by skirpichev** [comment]
> can you help me with some existing issues on sympy, which I will merge later

If these issues are relevant for the Diofant - yes.  Feel free to make PR.

**Comment by sachin-4099** [comment]
https://github.com/sympy/sympy/issues/14068
https://github.com/sympy/sympy/issues/18552

Currently I am working on these 2 issues

**Pull request merged**
