### PR TITLE
First Order Logic

### PR DESCRIPTION
**Pull request by skirpichev**
- [ ] better file names?
- [ ] Function class naming / better integration with the core Function/Application
- [ ] Add description to Exceptions
- [ ] use abc for abstract classes, if possible
- [ ] release notes, thanks
- [x] 100% test coverage

### CODE REVIEW

**Comment by skirpichev** [comment]
It seems, sympy/sympy#7608 will never be finished in the sympy.  I would like to do this for the diofant.  @sdbiswas, let me know if you disagree.  If you wish, I can mention you as a contributor.

**Comment by skirpichev** [comment]
@ghost, it seems you were interested in sympy/sympy#7608.  I have plans to add first order logic for the diofant (this will be required for CAD implementation) and use that work (at least partially).

**Comment by skirpichev** [comment]
@asmeurer, it seems your original contributor disappear from gh.  On which terms I can continue this work for the diofant?  Same is for #712 (in which case author already is in your AUTHORS file).

**Comment by sdbiswas** [comment]
@skirpichev My apologies for the delay in response.  I have no problems at all if you want to migrate this this work to diofant.

**Comment by skirpichev** [comment]
This pull request **introduces 1 alert** when merging 12a5ef2c7696df9b16906baafe32235984794b2c into 7601ad16c315f03e9219ddf0ae0bd4977bdce551 - [view on LGTM.com](https://lgtm.com/projects/g/diofant/diofant/rev/pr-6bedac905a12fddfbeb5d56e5c597550e78fecb2)

**new alerts:**

* 1 for First argument to super\(\) is not enclosing class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by skirpichev** [comment]
reopened in https://github.com/diofant/diofant/pull/877

**Pull request closed without merging**
