### PR TITLE
Finite fields for non-prime orders

### PR DESCRIPTION
**Pull request by skirpichev**
- [ ] ~~check on https://github.com/diofant/diofant/pull/712~~
- [x] release notes

see https://github.com/sympy/sympy/issues/13886 and https://github.com/sympy/sympy/issues/9544

c.f. https://reference.wolfram.com/language/FiniteFields/tutorial/FiniteFields.html

### CODE REVIEW

**Comment by skirpichev** [comment]
@cathreya, I saw you were [interested](https://github.com/sympy/sympy/issues/21104#issue-833106545) in prime-power finite fields in sympy?

Diofant has support for this since v0.11 (that include factorization of univariate polynomials over finite fields).  I doubt that SymPy's FiniteExtension's can help you here, i.e. to factorize polynomials over such domains.

It might be not as fast as it can, however.  `GF(2**m)` may worth a special implementation.

**Comment by cathreya** [comment]
@skirpichev, Thanks a lot for your reply. Diofant has come in handy to solve much of my problems! Is there any hack to get it to work with multivariate factorization as well? (I understand this is a big ask, but I am shooting my shot!)

**Comment by skirpichev** [comment]
On Wed, Mar 17, 2021 at 06:44:46AM -0700, cathreya wrote:
>    Is there any hack to get it to work with
>    multivariate factorization as well?

The general "hack" is the Hensel lifting.  But this is not implemented
yet for finite fields in the Diofant.  I'm not sure, but, perhaps,
there are better (specialized) variants for
finite fields (like square-free factorization, see e.g. "Factorization
of multivariate polynomials" by Martin Mok-Don Lee).  Patches are
welcome.

Factorization over finite fields in the Diofant - mostly a tool to
implement Zassenhaus algorithm for polynomials over ZZ.  That's why only
univariate factorization was implemented.  Fortunately, it does work
correctly, unlike SymPy, and over any finite field.

**Comment by skirpichev** [comment]
You might port algorithm implementations from the rings library.

For multivariate square-free factorization over fields of nonzero characteristics: the [Musser algorithm](https://github.com/PoslavskySV/rings/blob/ab602100d0ad572550a9fd44347675ba14f3c9a7/rings/src/main/java/cc/redberry/rings/poly/multivar/MultivariateSquareFreeFactorization.java#L205-L336).
For multivariate factorization: the [Kaltofen’s algorithm](https://github.com/PoslavskySV/rings/blob/ab602100d0ad572550a9fd44347675ba14f3c9a7/rings/src/main/java/cc/redberry/rings/poly/multivar/MultivariateFactorization.java#L187-L220).

**Pull request merged**
