### PR TITLE
WIP: latex/pretty: nth root notation for small integers and symbols

### LINKED ISSUE #888: nth-roots are not pretty printed
`pprint(7**(1/pi))` doesn't pretty print the `pi`.  See
https://github.com/sympy/sympy/pull/17620

Feel free to cherry-pick!

(Some of this doesn't effect diofant b/c `exp(-1)` is a `Pow`).

### PR DESCRIPTION
**Pull request by cbm755**
TODO

  - [x] pretty
  - [ ] latex
  - [x] tests
  - [x] adjust older tests
  - [x] refactor `_print_nth_root`.
  - [ ] decide on using this notation for symbols (not just integers)
  - [ ] decide on magic threshold: currently three digits
  - [ ] regression tests for closed issues

### CODE REVIEW

**Comment by skirpichev** [comment]
Probably, sympy/sympy#17616 may be also closed by this pr.  Please note, that I currently do mention closed sympy's issues in the release notes.

**Comment by cbm755** [comment]
Yes I'm doing this in SymPy too and will close that issue.

What do you think of this?  It still needs the LaTeX to do the same as pretty.  In particularly you can change the "magic number" 3 if you want.

**Comment by skirpichev** [comment]
> you can change the "magic number" 3 if you want.

Hmm, as I said before - latex output (e.g. with pdflatex) will be rendered fine for an arbitrary integer root.  But it seems that MathJax has problems already with 3 digits, maybe with 2.  Look:


With KaTeX this problem will gone, but I'm not sure that I'll replace MathJax soon - there are some problems in #865 (no linebreak analog) and there is no currently KaTeX support for Jupyter Notebook.  Thus, the practical boundary condition is: MathJax output must be fine for a given magic.  From the example above: 4 - doesn't work.  2-3 - maybe, 2 and 1 - ok.

With ``x_{17}`` - pdflatex output looks badly:

So, maybe using this radical symbol notation only for naturals (one digit?) - not a bad idea at all...

**Comment by cbm755** [comment]
And one-char symbols?  If so, magic number should be 1 in my pretty implementation (assuming we want latex and pretty to behave the same).

For latexprinter, need something other than width/len...

**Comment by skirpichev** [comment]
One-char symbols looks well, I can't provide bad examples.

**Comment by skirpichev** [comment]
@cbm755, simple fix for #888 was implemented in #891, feel free to review.

Let me know if you are willing to continue work for this pull request.  I feel, there is too much may be improved in nth-root printing (i.e. workaround for MathJax bug) and making latex vs pprint more consistent.

**Comment by skirpichev** [comment]
Ok, please reopen if you intend to finish this (or feel free to start a new pull request).

**Pull request closed without merging**
