### PR TITLE
dsolve: expm/jordan solver

### PR DESCRIPTION
**Pull request by skirpichev**
I hope @cbm755 ok if I continue [his work](https://github.com/sympy/sympy/pull/9235) here.

- [x] cleanup classify_sysode, drop redundant/untested code
- [x] cleanup tests/doctests
- [x] support mass matrix case, but see #293
- [x] don't simplify answer at all? (i.e. with sin/sinh)
- [x] drop unused sysode handlers, if any
- [x] good references (Hairer I?)
- [x] rename check_linear_order1_jordan-> check_linear_neq_order1,
       sysode_linear_order1_jordan -> sysode_linear_neq_order1
- [x] rebase

### CODE REVIEW

**Comment by cbm755** [comment]
No I don't mind, I wish I'd kept at this and fixed it in SymPy: I will still try.

Duplicated effort makes me sad :(

**Comment by skirpichev** [comment]
> No I don't mind

Good news, thank you for reply.

> I will still try.

Your code was sitting around in the pr queue for years without review...  So, good luck.

> Duplicated effort makes me sad :(

Are you about this project?  Yeah, but you know my history, at least partially.  That wasn't my idea to fork the SymPy, but now it is what it is.  For good or bad - now there is a different project with different goals and priorities.

**Comment by cbm755** [comment]
Oh sorry, I only meant this patch!  Did not mean your project.

**Comment by skirpichev** [comment]
Ok, now I think it's ready to be merged (to replace old horrible LODE solver).  Rewriting to sin/cos was reverted back, perhaps I'll add this later.

Solutions sometimes seems (with and without sin/cos rewriting) to be more complex (see tests changes), but I believe it worth, as new solver is much more simple.

Please tell me if you would like to review changes.

**Comment by skirpichev** [comment]
Anyway, thank you.

**Comment by vishalg2235** [comment]
@skirpichev @cbm755 I have made same changes as done here but my results are coming different.

like [here](https://github.com/sympy/sympy/blob/master/sympy/solvers/tests/test_ode.py#L57)
```
>>> eq3 = (Eq(diff(x(t),t), x(t) + y(t)), Eq(diff(y(t),t), -2*x(t) + 2*y(t)))
>>> dsolve(eq3)
[Eq(x(t), C1*(-2*sqrt(7)*I*(1/4 + sqrt(7)*I/4)*exp(t*(3 - sqrt(7)*I)/2)/7 + 2*sqrt(7)*I*(1/4 - sqrt(7)*I/4)*exp(t*(3 + sqrt(7)*I)/2)/7) + C2*((1/4 + sqrt(7)*I/4)*(1/2 + sqrt(7)*I/14)*exp(t*(3 - sqrt(7)*I)/2) + (1/4 - sqrt(7)*I/4)*(1/2 - sqrt(7)*I/14)*exp(t*(3 + sqrt(7)*I)/2))), Eq(y(t), C1*(-2*sqrt(7)*I*exp(t*(3 - sqrt(7)*I)/2)/7 + 2*sqrt(7)*I*exp(t*(3 + sqrt(7)*I)/2)/7) + C2*((1/2 + sqrt(7)*I/14)*exp(t*(3 - sqrt(7)*I)/2) + (1/2 - sqrt(7)*I/14)*exp(t*(3 + sqrt(7)*I)/2)))]
```
and [here](https://github.com/sympy/sympy/blob/master/sympy/solvers/tests/test_ode.py#L168)
```
>>> dsolve(e)
[Eq(f(x), C1*exp(-9*I*x)), Eq(g(x), C2*exp(-4*I*x))]
```
I think the form of answer is coming different.

**Comment by skirpichev** [comment]
Can't you just check math?

**Comment by vishalg2235** [comment]
Yes! Math is correct I'am just wondered why `C1*(-2*sqrt(7)*E**(t*(3 - sqrt(7)*I)/2)*I*(1/4 + sqrt(7)*I/4)/7` this has been changed to `C1*(-2*sqrt(7)*I*(1/4 + sqrt(7)*I/4)*exp(t*(3 - sqrt(7)*I)/2)/7 `. `E` is replaced by `exp`, terms with `I` is coming before `exp` in my results. Thats what I meant by 'form of answer'.

**Comment by asmeurer** [comment]
dsolve can be very sensitive to the form of solutions. That's why the dsolve tests were all written with checkodesol, to verify that the solution being tested is correct (it seems this practice was not extended to the systems tests). Generally, if the output form changes a little bit, you should just update the test (after verifying that the expression is still mathematically correct of course), unless it is significantly worse for some reason. 

In the case of `C1*(-2*sqrt(7)*E**(t*(3 - sqrt(7)*I)/2)*I*(1/4 + sqrt(7)*I/4)/7` vs. `C1*(-2*sqrt(7)*I*(1/4 + sqrt(7)*I/4)*exp(t*(3 - sqrt(7)*I)/2)/7`, these two expressions are identical. If you print them both in SymPy you will see that they both evaluate to the same thing. `E**` is the exact same thing as `exp`, and the order or arguments in a multiplication doesn't matter (`Mul` sorts them).

**Pull request merged**
