### PR TITLE
Backport some sympy fixes

### PR DESCRIPTION
**Pull request by skirpichev**
- [x] sympy/sympy#11546 - ok
- [x] sympy/sympy#11594 - no, garbage
- [x] sympy/sympy#11596 - fixed
- [x] sympy/sympy#11532 - no, nonlinsolve
- [x] sympy/sympy#11571 - no, MatrixElement._eval_derivative, not good
- [x] sympy/sympy#11590 - fixed
- [x] sympy/sympy#11232 - no, bad review, reverted later
- [x] sympy/sympy#11611 - no, seems bad
- [x] sympy/sympy#11603 - no
- [x] sympy/sympy#11616 - no, fixed
- [x] sympy/sympy#11601 - ok
- [x] sympy/sympy#11481 - no, Sum simplify - may be better
- [x] sympy/sympy#11627 - no, not "better"
- [x] sympy/sympy#11618 - no, maybe later
- [x] sympy/sympy#11631 - no, physics
- [x] sympy/sympy#11635 - no, fixed
- [ ] sympy/sympy#11589 - no, rings without gens, maybe?
- [x] sympy/sympy#11632 - no, AUTHORS
- [x] sympy/sympy#11647 - ok
- [x] sympy/sympy#11630 - no, done
- [x] sympy/sympy#11644 - no, authors_update.py
- [x] sympy/sympy#11649 - no, fixed
- [x] sympy/sympy#11652 - no, holonomic
- [ ] sympy/sympy#11241 - no, geometry, maybe later
- [x] sympy/sympy#11002 - no, physics
- [x] sympy/sympy#11675 - ok
- [x] sympy/sympy#11682 - no, fixed
- [x] sympy/sympy#11681 - no, fixed
- [x] sympy/sympy#11690 - no, garbage
- [x] sympy/sympy#11689 - no, concrete.guess
- [x] sympy/sympy#11695 - ok
- [x] sympy/sympy#11679 - no, symengine
- [ ] sympy/sympy#11693 - no, but think of
- [x] sympy/sympy#11698 - no, copy-pasted?
- [x] sympy/sympy#11663 - no, not "improved"
- [x] sympy/sympy#11705 - no, copy-pasted
- [x] sympy/sympy#11710 - no, we use pytest
- [x] sympy/sympy#11734 - no, concrete.guess
- [x] sympy/sympy#11714 - no, think about more simple solution
- [x] sympy/sympy#11747 - no, mess
- [x] sympy/sympy#11724 - no, fixed
- [x] sympy/sympy#11738 - ok
- [x] sympy/sympy#11748 - ok
- [x] sympy/sympy#11752 - no, fixed
- [x] sympy/sympy#11758 - no, physics
- [x] sympy/sympy#11767 - ok
- [x] sympy/sympy#11773 - no, garbage
- [x] sympy/sympy#11771 - no, fixed
- [x] sympy/sympy#11781 - no, garbage
- [x] sympy/sympy#11728 - no, quadrature
- [x] sympy/sympy#11788 - no issue
- [x] sympy/sympy#11780 - no issue
- [x] sympy/sympy#11784 - done
- [x] sympy/sympy#11794 - no, new stuff
- [x] sympy/sympy#11796 - no
- [x] sympy/sympy#11783 - no, UnevaluatedExpr
- [x] sympy/sympy#11800 - ok
- [x] sympy/sympy#11804 - ok
- [x] sympy/sympy#11792 - ok
- [x] sympy/sympy#11793 - ok
- [x] sympy/sympy#11825 - no, garbage
- [x] sympy/sympy#8386 - ok
- [x] sympy/sympy#11831 - no issue
- [x] sympy/sympy#11857 - no, UnevaluatedExpr
- [x] sympy/sympy#11851 - no
- [x] sympy/sympy#11687 - no, github stuff
- [x] sympy/sympy#11872 - no, setup.py
- [x] sympy/sympy#11846 - no, concrete.guess
- [x] sympy/sympy#11885 - no, another hack for gruntz
- [x] sympy/sympy#11883 - no, done
- [x] sympy/sympy#11862 - no, nsolve
- [x] sympy/sympy#11888 - no, nsolve
- [x] sympy/sympy#11886 - no, done
- [x] sympy/sympy#11822 - no, fixed
- [x] sympy/sympy#11897 - ok
- [x] sympy/sympy#11895 - no, examples
- [x] sympy/sympy#11859 - ok
- [x] sympy/sympy#11908 - no, garbage
- [x] sympy/sympy#11912 - no, fixed
- [x] sympy/sympy#11873 - no, new in geometry
- [x] sympy/sympy#11935 - no, sphinx build
- [x] sympy/sympy#11818 - no, Complexes
- [x] sympy/sympy#11919 - ok
- [x] sympy/sympy#11937 - no, travis
- [x] sympy/sympy#11939 - no, Complexes
- [x] sympy/sympy#11904 - no, new assumptions
- [x] sympy/sympy#11929 - no, their docs
- [x] sympy/sympy#11921 - no, wester test
- [x] sympy/sympy#11946 - no, Complexes
- [x] sympy/sympy#11369 - ok
- [x] sympy/sympy#11754 - ok
- [ ] sympy/sympy#11334 - no, permute signs in diophantine, think about
- [x] sympy/sympy#11933 - ok
- [x] sympy/sympy#11696 - no, fixed
- [x] sympy/sympy#11943 - no, py2
- [x] sympy/sympy#11398 - ok
- [x] sympy/sympy#11952 - no, new assumptions
- [ ] sympy/sympy#11874 - no, perf, maybe later
- [x] sympy/sympy#11965 - no, garbage
- [x] sympy/sympy#11947 - ok
- [x] sympy/sympy#11950 - no, fixed
- [x] sympy/sympy#11913 - ok
- [x] sympy/sympy#11910 - no, tensorflow
- [x] sympy/sympy#11906 - no, garbage
- [x] sympy/sympy#11867 - ok
- [x] sympy/sympy#11850 - ok
- [x] sympy/sympy#11791 - no, garbage
- [x] sympy/sympy#11790 - no, garbage
- [x] sympy/sympy#11907 - no, garbage
- [x] sympy/sympy#11751 - no, new stats stuff
- [x] sympy/sympy#11915 - ok
- [x] sympy/sympy#11866 - ok
- [x] sympy/sympy#11676 - ok, physics
- [x] sympy/sympy#11574 - no, sphinx
- [x] sympy/sympy#11567 - no, garbage
- [x] sympy/sympy#10982 - no
- [x] sympy/sympy#11076 - ok
- [x] sympy/sympy#10692 - ok
- [x] sympy/sympy#11980 - no issue
- [x] sympy/sympy#11889 - ok
- [x] sympy/sympy#11958 - no, garbage
- [x] sympy/sympy#11971 - no, garbage
- [ ] sympy/sympy#11954 - matrix cleanup, maybe later
- [x] sympy/sympy#11993 - no, physics
- [x] sympy/sympy#11940 - no, fixed
- [x] sympy/sympy#11116 - no, fixed
- [x] sympy/sympy#11454 - no, physics
- [x] sympy/sympy#11989 - ok
- [x] sympy/sympy#11995 - no, garbage
- [x] sympy/sympy#11984 - ok
- [x] sympy/sympy#12002 - no, garbage
- [x] sympy/sympy#11998 - no, better fix
- [x] sympy/sympy#11896 - ok
- [x] sympy/sympy#11951 - ok
- [x] sympy/sympy#11997 - ok
- [x] sympy/sympy#12008 - ok
- [x] sympy/sympy#12014 - no, README
- [x] sympy/sympy#11977 - ok
- [x] sympy/sympy#11853 - no, fourier series
- [x] sympy/sympy#11960 - ok
- [x] sympy/sympy#12022 - no, docs
- [x] sympy/sympy#12021 - no, expose dup_transpose (do we need this?)
- [x] sympy/sympy#12027 - no, copyright
- [x] sympy/sympy#11994 - no, travis
- [x] sympy/sympy#12037 - no, github
- [x] sympy/sympy#12031 - fixed
- [x] sympy/sympy#12039 - no, new assumptions
- [x] sympy/sympy#11572 - no, gsoc refs
- [x] sympy/sympy#11973 - no, rcode
- [x] sympy/sympy#12059 - no, travis
- [x] sympy/sympy#11787 - no, nsolve
- [x] sympy/sympy#12066 - no, fixed
- [x] sympy/sympy#12079 - no issue
- [x] sympy/sympy#12057 - no issue
- [x] sympy/sympy#12010 - ok
- [x] sympy/sympy#12102 - no, fixed
- [x] sympy/sympy#12065 - no, nsolve
- [x] sympy/sympy#12109 - ok
- [ ] sympy/sympy#12099 - no, perf, maybe later
- [x] sympy/sympy#12106 - no, nsolve
- [x] sympy/sympy#12105 - fixed
- [x] sympy/sympy#12096 - ok
- [x] sympy/sympy#12137 - ok
- [x] sympy/sympy#12075 - no, monotonicity_helper...
- [x] sympy/sympy#12119 - no, xnor
- [x] sympy/sympy#12138 - fixed
- [x] sympy/sympy#12121 - no, garbage
- [x] sympy/sympy#12141 - no, garbage
- [x] sympy/sympy#12061 - no, garbage
- [x] sympy/sympy#12148 - no, crypto
- [x] sympy/sympy#12036 - no, physics
- [x] sympy/sympy#12108 - ok
- [x] sympy/sympy#12150 - no, fixed
- [x] sympy/sympy#12165 - no, nsolve
- [x] sympy/sympy#12166 - ok
- [x] sympy/sympy#12167 - copy-pasted
- [x] sympy/sympy#12176 - no, fixed
- [ ] sympy/sympy#12142 - no, improve singularities() first
- [x] sympy/sympy#12184 - no, fixed
- [x] sympy/sympy#12174 - no, interactive
- [x] sympy/sympy#12183 - ok
- [x] sympy/sympy#11970 - no, think of
- [x] sympy/sympy#12195 - ok
- [x] sympy/sympy#12171 - no, fixed
- [x] sympy/sympy#12216 - ok
- [x] sympy/sympy#12206 - no, floor/ceiling
- [x] sympy/sympy#12201 - ok
- [x] sympy/sympy#10531 - fixed
- [x] sympy/sympy#12207 - no, physics
- [x] sympy/sympy#12232 - no, UnevaluatedExpr
- [x] sympy/sympy#12240 - ok
- [x] sympy/sympy#12244 - ok
- [x] sympy/sympy#12194 - no
- [x] sympy/sympy#12236 - ok
- [ ] sympy/sympy#12040 - no, need better
- [x] sympy/sympy#12253 - no, manualintegrate
- [x] sympy/sympy#12255 - ok
- [x] sympy/sympy#12222 - not broken
- [x] sympy/sympy#12281 - no
- [x] sympy/sympy#12247 - no, nsolve

-------------------------------------

Last pr: #598

### CODE REVIEW

**Comment by skirpichev** [comment]
@jksuom, it seems you last reviewed https://github.com/sympy/sympy/pull/11546.  I think there is a bug in the function (with a very bad test coverage, surprisingly) `_discrete_log_pollard_rho()`, as it returns apparently wrong answer:
```
In [1]: from sympy.ntheory.residue_ntheory import _discrete_log_pollard_rho

In [2]: n, a, b = 11, 7, 31; _discrete_log_pollard_rho(n, a, b, rseed=0)
Out[2]: 2

In [3]: (b**2 - a)%n
Out[3]: 8
```
What do you think?

**Comment by jksuom** [comment]
I'll have to take some time to look into this. It is possible that there is a bug.

**Comment by skirpichev** [comment]
BTW, all other implemented algorithms raise ValueError's in that case, as expected, and the Mathematica returns unevaluated expression, that means there is no logarithm for the given values (notice different call convention for the MultiplicativeOrder):
```
In[1]:= MultiplicativeOrder[7, 41, {15}]

Out[1]= 3

In[2]:= MultiplicativeOrder[3, 24567899, {3^333}]

Out[2]= 333

In[3]:= MultiplicativeOrder[31, 11, {7}]

Out[3]= MultiplicativeOrder[31, 11, {7}]
```
IIUC, `_discrete_log_pollard_rho()` may raise ValueError if the logarithm exists (in case of bad luck), but otherwise it shouldn't return a wrong answer.

**Comment by jksuom** [comment]
It seems that the algorithm in the handbook is slightly simplified. It assumes that the order of the multiplicative group is a prime, in which case any nontrivial  `b`  is a generator. In the example, `b = 31` is not a generator. The algorithm will mostly work without that assumption, but I think that `mod_inverse(r, order) * (ab - aa) % order` should be checked before it is returned.

**Comment by skirpichev** [comment]
Hmm, another thing, apparently broken in sympy after sympy/sympy#12236.

Here [the latest failure](https://travis-ci.org/diofant/diofant/jobs/492687048) in this PR:
```
    def test_PolynomialRing_from_FractionField():
        F,  x, y = field("x,y", ZZ)
        R,  X, Y = ring("x,y", ZZ)
    
        f = (x**2 + y**2)/(x + 1)
        g = (x**2 + y**2)/4
        h = x**2 + y**2
    
        pytest.raises(CoercionFailed, lambda: R.convert(f, F))
>       assert R.convert(g, F) == X**2/4 + Y**2/4
...
diofant/domains/domain.py:88: CoercionFailed
```

But in SymPy this test was:
```
R.to_domain().from_FractionField(g, F.to_domain()) == X**2/4 + Y**2/4
```
The lhs in None after sympy/sympy#12236.  But the right hand side is `R.zero`, and that *is* equal to `None` due to funny property of PolyElement's `__eq__`: R.zero == None.

**Comment by skirpichev** [comment]
Is https://github.com/sympy/sympy/pull/11589 intended to be useful after switching to the sparse polynomial representation in Poly class?  As it's now, this doesn't offer any way of "convenient construction of coefficient domains" for users, only make things more complex.

**Comment by jksuom** [comment]
Some functions like `sring` and `sfield` used to raise an exception if the input expressions contain no variables. The change was made to avoid having to set up explicit try-except blocks for each use of those functions. In such contexts, there are usually also polynomials with variables, and the zero variable rings should unify with them in algebraic operations. Otherwise, they should obviously be avoided.

**Comment by skirpichev** [comment]
> The change was made to avoid having to set up explicit try-except blocks for each use of those functions.

Hmm, any other example, except sring/sfield?

BTW, your handling of degrees is not consistent at least:
```
In [14]: R, = ring('', ZZ)

In [15]: R(2).degree()
Out[15]: 0

In [16]: R(2).tail_degree()
Out[16]: 0

In [17]: R(2).degrees()
Out[17]: ()
```
I would expect `tail_degree()/degree()` will return `None` instead.

**Comment by jksuom** [comment]
I agree that those methods have not been implemented properly.

**Comment by skirpichev** [comment]
`None` sounds OK, or you prefer if `degrees()` will return instead a tuple of len==1?

**Comment by jksuom** [comment]
I would consider polynomial rings as graded algebras with gradation N^n. Various degrees should be derived from homomorphisms  N^n -> N (with the convention that the zero polynomial, with no representative in N^n, is mapped to -oo).
For n = 0, N^n is the trivial monoid that consists of the zero element only. Formally, that element is the empty tuple (). There is a single homomorphism N^0 -> N that takes () to 0. Therefore, I think it conceivable that a non-zero polynomial could have degree 0. `None` seems inconvenient to deal with. Alternatively, if we want `degree` to be always associated with an indeterminate, which does not exist, then perhaps an exception should be raised.
`tail_degree` is another matter. Maybe it could be the same as `degree`, if anything.
Finally, I think that () is a reasonable result for `degrees`.

**Comment by skirpichev** [comment]
> Alternatively, if we want degree to be always associated with an indeterminate, which does not exist, then perhaps an exception should be raised.

Hmm, I'm not sure if this will be more convenient than `None`.

> Finally, I think that () is a reasonable result for degrees.

That apparently violates the function docstring: `A tuple containing leading degrees in all variables.`  If `degree()` will return `0` or `-oo` - the returned by `degrees()` tuple can't be empty.

Last, but not least, sympy/sympy#11589 make dense and sparse representations - incompatible.

**Comment by jksuom** [comment]
I think that `degree()` with no arguments could be interpreted as a 'default' degree, not necessarily a degree wrt a variable when there are none. (Its docstring could be changed.) So, strictly speaking, `degrees` could be the empty tuple.

**Comment by skirpichev** [comment]
https://github.com/sympy/sympy/pull/11989 claims it "fixes" https://github.com/sympy/sympy/issues/11956, yet in the current sympy master:
```
In [1]: diophantine(2*x**2 + y**2 - 16)
Out[1]: set()
```
Either it wasn't fixed at all, or there is a regression (not surprising, as there was no regression test).

**Comment by skirpichev** [comment]
sympy/sympy#2537 was mentioned as "closed" in https://github.com/sympy/sympy/pull/11896, yet there is no regression test.  And in the current SymPy it happens to give a funny answer:
```
In [1]: var('a, l')
Out[1]: (a, l)

In [2]: Integral((a/sqrt(x**2+a**2))**3,(x,-l,l))
Out[2]: 
l                 
⌠                 
⎮        3        
⎮       a         
⎮  ──────────── dx
⎮           3/2   
⎮  ⎛ 2    2⎞      
⎮  ⎝a  + x ⎠      
⌡                 
-l                

In [3]: _.doit()
Out[3]: 0

```

**Comment by skirpichev** [comment]
Ok, I think I should revert sympy/sympy#11589 (rings without generators).  It makes different polynomial representations incompatible, has no clear practical needs (except very high-level stuff like sring) and require introducing (and explaining) a lot of special cases.

**Comment by jksuom** [comment]
I agree that PolyRings with no generators are not a very good idea. It would probably be a better solution to catch the generator errors and create a simple domain instead. (I may have to think about it.) Besides, I always thought that the monomial manipulations of PolyRings are more complicated than would have been necessary.

**Comment by skirpichev** [comment]
> It would probably be a better solution to catch the generator errors and create a simple domain instead.

In cases of sring/sfield - exceptions are fine.  These functions are mostly for interactive usage.

> I always thought that the monomial manipulations of PolyRings are more complicated than would have been necessary.

Any simplifications here are welcome, I'll watch your efforts.  After merging #795 - sparse polynomials will be a most important workhorse in the Diofant codebase.

**Pull request merged**
