### PR TITLE
Using encoded integer polynomials to speed up dup_mul()

### PR DESCRIPTION
**Pull request by skirpichev**
- [x] change commit authorship
- [ ] ask for permission
- [ ] gf_mul
- [ ] benchmark

### CODE REVIEW

**Comment by skirpichev** [comment]
@pernici, let me know if you are not ok with merging your work to the diofant on it's [license](https://github.com/diofant/diofant/blob/master/LICENSE.rst) terms (your work is not merged yet to the sympy, so I can't assume sympy license holds on it).

**Comment by pernici** [comment]
Hello Sergey
  please close this WIP, I do no remember anything worth merging.

**Comment by skirpichev** [comment]
> I do no remember anything worth merging.

Port (to the diofant) of Fateman's arlorithm in sympy/sympy#2845

> please close this WIP

Ok, done.  As I said, I don't assume your code is open source and may be distributed on SymPy's terms.

**Comment by skirpichev** [comment]
@czgdp1807, I'm sorry to miss [your question](https://github.com/sympy/sympy/pull/2845#issuecomment-586729074) - FYI, blocked users will not be notified if you mention them in repo where you block them.

This is the port of the Fateman's [multiplication algorithm](https://people.eecs.berkeley.edu/~fateman/papers/polysbyGMP.pdf) from https://github.com/sympy/sympy/pull/2845.  Unfortunately, SymPy's author wont permit to use his work in the Diofant, so - this pr was closed.  Now it can't be merged, as the Diofant's polys module don't use the dense polynomial representation.

**Pull request closed without merging**
