### PR TITLE
New factorization algorithm for polynomials over algebraic number fields

### PR DESCRIPTION
**Pull request by skirpichev**
This is a continuation of work in sympy/sympy#2468 and https://github.com/diofant/diofant/pull/712.

Todo:
- [x] ResidueRing -> FiniteRing or QuotientRing?
- [x] full test coverage
- [x] don't use `ring.dmp_LC`
- [x] split out https://github.com/sympy/sympy/commit/b5986e84801a305fafc51827ca40ef010d322925 and https://github.com/sympy/sympy/commit/f52f756b911c529c41c303924542ebf8d0f98f4c?
- [ ] better file/functions names?
- [x] changes for rref/solve_lin_sys?
- [x] rebase & cleanup
- [x] release notes
- [x] up-to-date benchmark
- [x] change this to be a default factorization method for algebraic fields?
- [ ] address TODO
- [ ] check tests

@katjasophie, I assume, I can use your unmerged yet work from sympy/sympy#2468 to the Diofant on terms of the usual SymPy license.  Please reply, if you are disagreed.

Some benchmarks on my system:
```
In [2]: R, x, y = ring('x, y', QQ.algebraic_field(sqrt(2)))
   ...: f = (x + y)*(x**2 + sqrt(2)*y)
   ...: %timeit efactor(f)
   ...: %timeit f.factor_list()
350 ms ± 3.83 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
226 ms ± 875 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [3]: R, x, y, z = ring('x, y, z', QQ.algebraic_field(root(2, 5)))
   ...: f = (x - y)*(x**2*y + root(2, 5)*y**2*z)
   ...: %timeit efactor(f)
   ...: %timeit f.factor_list()
514 ms ± 12.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.44 s ± 545 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [4]: R, x, y, z = ring('x, y, z', QQ.algebraic_field(sqrt(2), root(3, 3)))
   ...: f = (x**2 + 2*y + sqrt(2))*(root(3, 3)*x - z)
   ...: %timeit efactor(f)
   ...: %timeit f.factor_list()
2.66 s ± 141 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
47.4 s ± 2.39 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

New algorithm is clearly better for extensions with high degrees.

### CODE REVIEW

**Comment by skirpichev** [comment]
Using the quotient rings `Z/p^nZ` seems to be a solution for wiping out the modifications in the matrices module.  This was the major issue with this stuff so far (second one - bad code coverage).

The original author (she was in SymPy's AUTHORS) seems to be unresponsive.  @asmeurer, may I ask you for permission to merge this stuff on the terms of the usual SymPy license?

**Comment by skirpichev** [comment]
@jksuom, it seems that Matrix.rref() can work with coefficients in `Z/nZ`, making the matrices module modifications in the sympy/sympy#2468 - unnecessary.

I'm not so sure about naming stuff.  `ResidueRing` now is for quotient rings `Z/nZ` (and I use FiniteField's in the case `n` - prime).  `FiniteRing`?

**Comment by jksuom** [comment]
Clearly, FiniteRing is better than FiniteField, and probably could be used, but, of course, there are other finite rings than Z/nZ.

**Comment by skirpichev** [comment]
> Clearly, FiniteRing is better than FiniteField

No.  FiniteField's are in the Diofant on own purpose: they are for (surprise!) finite fields (both prime and prime power orders).

But for this PR, quotient rings Z/nZ were added: c1c07003.  I was thinking about naming them.

**Comment by jksuom** [comment]
That is how I understood it: Z/nZ. It could be named FiniteRing (which is better than FiniteField in SymPy).

**Comment by skirpichev** [comment]
QuotientRing is an alternative for ResidueRing (or FiniteRing) I was thinking of.

But that sounds as a very generic construction, which would require implementing some classes for ideals, while right now I'm interested mainly in a very limited case (principal ideals, see e.g. QuotientRingElement, which was used to represent ResidueRing, FiniteField and AlgebraicField elements).

**Comment by asmeurer** [comment]
I can't give permission for other people's work, but I think it would be safe to assume that any pull request to SymPy is released under the SymPy license.

**Comment by skirpichev** [comment]
Thank you, @asmeurer, I thought the same.

BTW, it's not a clear why https://github.com/sympy/sympy/pull/2468 wasn't merged in the SymPy.  As the bad (!=100%) code coverage isn't an issue for SymPy - the only blocking thing IMHO could be matrices/solve_lin_sys modifications.  It seems, this can be solved like I did here with the "ResidueRing" (which actually does in Diofant that the FiniteField does for SymPy).

**Comment by skirpichev** [comment]
BTW, doesn't help with https://github.com/sympy/sympy/issues/19196

**Comment by skirpichev** [comment]
I feel, this is in a relatively good shape now.  Lets try to merge.

> I think it would be safe to assume that any pull request to SymPy is released under the SymPy license.

@asmeurer, maybe you could document this somehow?

It seems apparent, that the original pr https://github.com/sympy/sympy/pull/2468 is not going to be merged in the SymPy in near future (and I can't help here for obvious to you and Ondrej reasons)...

**Comment by skirpichev** [comment]
Current benchmarks.

On the master:
```
In [3]: A = QQ.algebraic_field(sqrt(2), root(3, 3))
      : R, x, y, z = ring('x y z', A)
      : 

In [4]: f2, f1 = x**2 + 2*y + sqrt(2), x - z/root(3, 3)
      : f = f1*f2
      : %time assert f.factor_list() == (1, [(f1, 1), (f2, 1)])
      : 
CPU times: user 5min 59s, sys: 540 ms, total: 6min
Wall time: 6min 1s
```

On this branch:
```
In [2]: f2, f1 = x**2 + 2*y + sqrt(2), x - z/root(3, 3)
      : f = f1*f2
      : %time assert f.factor_list() == (1, [(f1, 1), (f2, 1)])
CPU times: user 24 s, sys: 83.7 ms, total: 24.1 s
Wall time: 24.4 s
```

The test was taken from https://github.com/sympy/sympy/issues/19196 (with a little adaptation: division to root(3, 3) of the second polynomial).

**Comment by skirpichev** [comment]
> That is how I understood it: Z/nZ. It could be named FiniteRing

In the end, this seems to be a bad idea.  Already for order=4 there are 2 (commutative) rings and 1 field, which are not isomorphic to the Z/4Z.

Maybe IntegerModRing, like Sage?

**Pull request merged**
