### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by skirpichev**

### CODE REVIEW

**Comment by skirpichev** [comment]
@jksuom, https://github.com/sympy/sympy/issues/16038 has problems not just with floats vs exact input.  In this case SymPy's function also returns an incomplete solution set (2 of 8 solutions).  See my regression test: 92aae4fc5.

BTW, I think the RootOf._eval_evalf() helper is wrong (both in the Diofant and in the SymPy).  There are no checks to ensure it returns the `prec` number of exact binary digits.

**Comment by jksuom** [comment]
> SymPy's function also returns an incomplete solution set (2 of 8 solutions).

It has been my understanding that the implementations is incomplete.

> There are no checks to ensure it returns the prec number of exact binary digits.

Thanks for telling. Perhaps that would not be hard to fix.

**Comment by skirpichev** [comment]
On Sat, Feb 23, 2019 at 05:08:40AM -0800, Kalevi Suominen wrote:
>    Thanks for telling. Perhaps that would not be hard to fix.

I'm figuring out an example of such a failure.  Not sure if it would
be an easy to fix issue.  Probably, some combination of findroot
with inteval.refine() will work.

But I'm thinking about optimization
for refinement of complex roots by semi-numerical methods, instead
of using the Collins-Krandick algorithm (see e.g.
https://doi.org/10.1006/jsco.1997.0158).  This will make
the present _eval_evalf() helper more or less obsolete.

**Comment by jksuom** [comment]
> refinement of complex roots by semi-numerical methods,

That sounds interesting.

**Comment by skirpichev** [comment]
> I'm figuring out an example of such a failure.

Hmm, that was a hard task.

However, I discovered yet another problem for sympy:
```
In [1]: %time r3 = RootOf(x**5 + 11111111111111*x - 1, 3)
CPU times: user 11.1 s, sys: 117 ms, total: 11.2 s
Wall time: 12.2 s

In [2]: tuple(map(lambda x: complex(*x), r3.interval.as_tuple()))  # r3._get_interval() in sympy
Out[2]: ((646.7517879274092-1293.5035758548183j), (1293.5035758548183-646.7517879274092j))

In [3]: %time nroots(r3.poly.as_expr())
CPU times: user 42.5 ms, sys: 404 µs, total: 42.9 ms
Wall time: 48.2 ms
Out[3]: 
[9.00000000000009e-14, -1290.9944487358 - 1290.9944487358⋅ⅈ, -1290.9944487358 + 1290.9944487358⋅ⅈ, 1290.9944487358 - 1290.9944487358⋅
ⅈ, 1290.9944487358 + 1290.9944487358⋅ⅈ]

In [4]: %time r3.evalf()
CPU times: user 5.52 s, sys: 7.38 ms, total: 5.53 s
Wall time: 5.62 s
Out[4]: 1290.9944487358 - 1290.9944487358⋅ⅈ

In [5]: str(_3[3]) == str(_4)
Out[5]: True
```
SymPy's version hangs on In[4] for a half hour, maybe forever.

**Pull request merged**
